name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.6.1]
    env:
      MONGODB_URL: ${{secrets.MONGODB_URL}}
      
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present

    - name: Change Directory
      run: cd /home/pluto/actions-runner/_work/Ecommerce-RESTFUL-API/Ecommerce-RESTFUL-API
    
    - run: pm2 restart 0